import type { Metadata } from "next";
import localFont from "next/font/local";
import { GoogleAnalytics } from "@next/third-parties/google";
import QueryProvider from "@/components/provider/QueryProvider";
import "./globals.css";

const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${pretendard.variable}`}>
      <body className={`${pretendard.className} antialiased`}>
        <QueryProvider>
          <main className="max-w-[600px] mx-auto h-dvh shadow-lg">
            {children}
          </main>
        </QueryProvider>
      </body>
      <GoogleAnalytics gaId="G-BXMPGJ5BMX" />
    </html>
  );
}
